#!/usr/bin/perl

# deps
  use strict;
  use warnings;

# ---   *   ---   *   ---

my $infont=glob($ARGV[0]);
my $intable=glob($ARGV[1]);

# generate table and open for read
system 'psfgettable',($infont,$intable);
open FH,'<',$intable or die $!;

# readlines
my @lines=();while(my $line=<FH>) {
  if(!$line) {next;};
  if((index $line,'#') eq 0) {
    push @lines,$line;next;

  };


  # capture keycode
  $line=~ s/0x([\w|\d]+)\s+//;
  my $kc=hex $1;

  # ensure keycode corresponds to char
  push @lines,sprintf (
    "0x%02X U+%04x U+%04x\n",
    $kc,$kc,256+$kc

  );
  

};close FH;

# ---   *   ---   *   ---

# now dump buffer
open FH,'>',$intable or die $!;

while(@lines) {
  print FH shift @lines;

};close FH;


# ---   *   ---   *   ---
1; # ret;
